// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.VideoClipper = (function() {
    VideoClipper.prototype.vid = "";

    VideoClipper.prototype.start_time = "";

    VideoClipper.prototype.end_time = "";

    VideoClipper.prototype.video_type = "";

    VideoClipper.prototype.answer_class = "bookMarklet-answer";

    VideoClipper.prototype.reel = 'http://web.mit.edu/colemanc/www/bookmarklet/images/film3Small.png';

    VideoClipper.prototype.modal_id = "";

    VideoClipper.prototype.player = false;

    VideoClipper.prototype.playerV = false;

    VideoClipper.prototype.caretPos = 0;

    function VideoClipper(obj) {
      this.getCaretPosition = __bind(this.getCaretPosition, this);
      this.generateSnippetBox = __bind(this.generateSnippetBox, this);
      this.generateVideoBox = __bind(this.generateVideoBox, this);
      this.generateBLDataString = __bind(this.generateBLDataString, this);
      this.generateTag = __bind(this.generateTag, this);
      this.generateURL = __bind(this.generateURL, this);
      this.YTOnPlayerReady = __bind(this.YTOnPlayerReady, this);
      this.update = __bind(this.update, this);
      this.clearInputs = __bind(this.clearInputs, this);
      this.modalOpen = __bind(this.modalOpen, this);
      this.getBLData = __bind(this.getBLData, this);
      this.create = __bind(this.create, this);
      this.checkErrors = __bind(this.checkErrors, this);
      this.close_modal = __bind(this.close_modal, this);
      this.setup = __bind(this.setup, this);      obj = obj || {};
      this.reel = obj.reel || this.reel;
      this.answer_class = obj.answerClass || this.answer_class;
    }

    VideoClipper.prototype.setup = function() {
      var that,
        _this = this;

      console.log("here");
      that = this;
      if ($("#bl").length === 0) {
        this.generateSnippetBox();
      }
      if ($("#bl-vid").length === 0) {
        this.generateVideoBox();
      }
      if ($("#bookMarklet-overlay").length === 0) {
        $("<div id='bookMarklet-overlay'></div>").appendTo("body");
      }
      $("#bookMarklet-overlay").click(function() {
        return _this.close_modal(_this.modal_id);
      });
      $(document).on("click", "." + this.answer_class, function() {
        that.caretPos = that.getCaretPosition(this);
      });
      $(document).on("keyup", "." + this.answer_class, function() {
        var div_text;

        that.caretPos = that.getCaretPosition(this);
        div_text = $(this).html();
        $(this).prev().val(div_text);
      });
      $(document).on("click", "[rel*=blModal]", function() {
        that.modalOpen(this);
      });
      $(".bl-start").click(function(e) {
        var curr_time;

        curr_time = _this.player.getCurrentTime();
        $("input[name='bl-start']").val(curr_time);
        that.checkErrors();
      });
      $(".bl-end").click(function(e) {
        var curr_time;

        curr_time = _this.player.getCurrentTime();
        $("input[name='bl-end']").val(curr_time);
        that.checkErrors();
      });
      $(".bl-done").click(function(e) {
        that.close_modal(_this.modal_id);
        that.update(that.generateTag());
      });
      return $(".bl-reset").click(function(e) {
        that.clearInputs();
        _this.player.loadVideoById(_this.vid, 0, "large");
      });
    };

    VideoClipper.prototype.close_modal = function(modal_id) {
      $("#bookMarklet-overlay").fadeOut(200);
      $(modal_id).css({
        display: "none"
      });
      if (modal_id === "#bl") {
        return this.player.stopVideo();
      } else {
        if (this.modal_id === "#bl-vid") {
          return this.playerV.stopVideo();
        }
      }
    };

    VideoClipper.prototype.checkErrors = function() {
      this.start_time = parseFloat($("input[name='bl-start']").val());
      this.end_time = parseFloat($("input[name='bl-end']").val());
      if ((this.start_time < this.end_time || isNaN(this.end_time)) && (!isNaN(this.start_time))) {
        $("input[name='bl-start']").removeClass("bl-incorrect");
        $("input[name='bl-end']").removeClass("bl-incorrect");
        return true;
      } else {
        $("input[name='bl-start']").addClass("bl-incorrect");
        $("input[name='bl-end']").addClass("bl-incorrect");
        return false;
      }
    };

    VideoClipper.prototype.create = function(textareaid, videotype, videoid, button) {
      var blDataEncoded, dataString,
        _this = this;

      $("#" + textareaid).each(function(index, element) {
        var content, h, w;

        w = $(element).width();
        h = $(element).height();
        content = $(element).val();
        $(element).after("<div></div>").css("display", "none").next().attr({
          contenteditable: "true"
        }).addClass(_this.answer_class).css({
          width: w,
          height: h
        });
      });
      dataString = this.generateBLDataString({
        type: "generate",
        vid: videoid,
        vtype: videotype
      });
      blDataEncoded = encodeURI(dataString);
      if (button) {
        return $("." + this.answer_class).after("<input type='button' value='Snippet'>").next().attr({
          "data-bl": blDataEncoded,
          rel: "blModal"
        });
      }
    };

    VideoClipper.prototype.getBLData = function(el) {
      var blData;

      blData = void 0;
      if (typeof ($(el).attr("data-bl")) !== "undefined") {
        blData = $.parseJSON(decodeURI($(el).attr("data-bl")));
      } else {
        if (typeof ($(el).text()) !== "undefined") {
          blData = $.parseJSON(decodeURI($(el).text()));
        }
      }
      return blData;
    };

    VideoClipper.prototype.modalOpen = function(el) {
      var blData, modal_width, that, url;

      that = this;
      blData = that.getBLData(el);
      if (blData.type === "generate") {
        this.vid = blData.video.id;
        this.video_type = blData.video.type;
        url = "";
        if (this.video_type === "yt") {
          url = "http://www.youtube.com/embed/" + this.vid;
        }
        $(".bl-srcURL").attr("href", url);
        $(".bl-srcURL").text(url);
        that.clearInputs();
        if (this.player === false) {
          this.player = new window.YT.Player("bl-player", {
            videoId: this.vid,
            events: {}
          });
        } else {
          this.player.cueVideoById(this.vid, 0, "large");
        }
      } else {
        this.vid = blData.video.id;
        this.start_time = blData.start;
        this.end_time = blData.end;
        this.video_type = blData.video.type;
        if (this.playerV === false) {
          this.playerV = new YT.Player("bl-playerV", {
            videoId: this.vid,
            events: {
              onReady: that.YTOnPlayerReady
            }
          });
        } else {
          this.playerV.cueVideoById({
            videoId: this.vid,
            startSeconds: this.start_time,
            endSeconds: this.end_time,
            suggestedQuality: "large"
          });
        }
      }
      this.modal_id = blData.modal;
      modal_width = $(this.modal_id).outerWidth();
      $("#bookMarklet-overlay").css({
        display: "block",
        opacity: 0
      });
      $("#bookMarklet-overlay").fadeTo(200, 0.5);
      $(this.modal_id).css({
        display: "block",
        position: "fixed",
        opacity: 0,
        "z-index": 11000,
        left: 50 + "%",
        "margin-left": -(modal_width / 2) + "px",
        top: "100px"
      });
      return $(this.modal_id).fadeTo(200, 1);
    };

    VideoClipper.prototype.clearInputs = function() {
      $("input[name='bl-end']").val("");
      $("input[name='bl-start']").val("");
      $("input[name='bl-start']").removeClass("bl-incorrect");
      $("input[name='bl-end']").removeClass("bl-incorrect");
      return $(".bl-URL").text("Generated URL goes here");
    };

    VideoClipper.prototype.update = function(newLink) {
      var beginPos, blData, currContent, endPos, newContent, newVal, srcQues,
        _this = this;

      $(".bl-URL").text(newLink);
      blData = encodeURI(this.generateBLDataString({
        type: "generate"
      }));
      srcQues = "[data-bl='" + blData + "']";
      currContent = $("." + this.answer_class).contents();
      newContent = [];
      beginPos = 0;
      endPos = 0;
      if (currContent.length === 0) {
        newContent = newLink;
      } else {
        currContent.each(function(i, e) {
          var back, eString, front;

          if (((e.nodeType === 3) || (e.nodeType === 1)) && (endPos < _this.caretPos)) {
            eString = "";
            if (e.nodeType === 3) {
              eString = e.data;
            } else {
              eString = e.text;
            }
            beginPos = endPos;
            endPos = endPos + eString.length;
            if (endPos >= _this.caretPos) {
              front = eString.substring(0, _this.caretPos - beginPos);
              back = eString.substring(_this.caretPos - beginPos, eString.length);
              newContent = newContent.concat(front);
              newContent = newContent.concat(newLink);
              newContent = newContent.concat(back);
            } else {
              newContent = newContent.concat(e);
            }
          } else {
            newContent = newContent.concat(e);
          }
        });
      }
      $("." + this.answer_class).text("");
      $(newContent).each(function(i, e) {
        return $("." + _this.answer_class).append(e);
      });
      newVal = $("." + this.answer_class).html();
      return $("." + this.answer_class).prev().val(newVal);
    };

    VideoClipper.prototype.YTOnPlayerReady = function(event) {
      return event.target.cueVideoById({
        videoId: this.vid,
        startSeconds: this.start_time,
        endSeconds: this.end_time,
        suggestedQuality: "large"
      });
    };

    VideoClipper.setup_yt = function() {
      var firstScriptTag, tag;

      tag = document.createElement("script");
      tag.src = "https://www.youtube.com/iframe_api";
      firstScriptTag = document.getElementsByTagName("script")[0];
      return firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    };

    VideoClipper.prototype.generateURL = function(obj) {
      var endTime, startTime, vidURL, videoID;

      obj = obj || {};
      vidURL = "http://www.youtube.com/v/";
      videoID = obj.vid || this.vid;
      startTime = obj.start || this.start_time;
      endTime = obj.end || this.end_time;
      vidURL = vidURL + videoID + "&start=" + startTime + "&end=" + endTime + "&version=3";
      return vidURL;
    };

    VideoClipper.prototype.generateTag = function() {
      var blDataEncoded, dataString, end, newTag, start;

      this.start_time = $("input[name='bl-start']").val();
      this.end_time = $("input[name='bl-end']").val();
      if (this.checkErrors()) {
        $("input[name='bl-start']").removeClass("bl-incorrect");
        $("input[name='bl-end']").removeClass("bl-incorrect");
        if (this.end_time === "") {
          this.end_time = this.player.getDuration();
        }
        start = new Date(null);
        end = new Date(null);
        start.setSeconds(this.start_time);
        end.setSeconds(this.end_time);
        start = start.toTimeString().substr(3, 5);
        end = end.toTimeString().substr(3, 5);
        newTag = "";
        dataString = this.generateBLDataString({
          type: "show"
        });
        blDataEncoded = encodeURI(dataString);
        newTag = $("<a rel='blModal' href='#bl-vid' class='bl'>" + blDataEncoded + "</a>").css({
          'background-image': this.reel
        });
        return newTag;
      } else {
        return "";
      }
    };

    VideoClipper.prototype.generateBLDataString = function(obj) {
      var dataEnd, dataStart, dataString, dataVType, dataVid;

      obj = obj || {};
      dataString = "";
      dataVid = obj.vid || this.vid;
      dataVType = obj.vtype || this.video_type;
      if (obj.type === "generate") {
        dataString = "{\"type\": \"generate\", \"modal\": \"#bl\"," + "\"video\": {" + "\"id\": \"" + dataVid + "\", \"type\": \"" + dataVType + "\"}}";
      } else if (obj.type === "show") {
        dataStart = obj.start || this.start_time;
        dataEnd = obj.end || this.end_time;
        dataString = "{\"start\": \"" + dataStart + "\", \"end\": \"" + dataEnd + "\", \"type\": \"show" + "\", \"modal\": \"#bl-vid" + "\", \"video\": {" + "\"id\": \"" + dataVid + "\", \"type\": \"" + dataVType + "\"}}";
      }
      return dataString;
    };

    VideoClipper.prototype.generateVideoBox = function() {
      return $("<div id='bl-vid'><div class='bl-video-wrap'>" + "<div id='bl-playerV'></div>" + "</div></div>").appendTo("body");
    };

    VideoClipper.prototype.generateSnippetBox = function() {
      return $("<div id='bl'>" + "<div class='bl-top'>" + "<div class='bl-vid'>" + "<div id='bl-player'></div>" + "</div>" + "<div class='bl-controls'>" + "<div class='bl-title'>" + "<h1>Create a URL</h1>" + "</div>" + "<div class='bl-instructions'>" + "Click \"Start Time\" and \"End Time\" buttons," + "or by type in the time in the text boxes." + "</div>" + "<table class='bl-input'>" + "<tr>" + "<td>" + "<input class='bl-button bl-start' type='button' value='Start Time'>" + "</td>" + "<td>" + "</td>" + "<td>" + "<input class='bl-button bl-end' type='button' value='End Time'>" + "</td>" + "</tr>" + "<tr>" + "<td>" + "<input class='bl-data' type='text' name='bl-start'>" + "</td>" + "<td>" + "-" + "</td>" + "<td><input class='bl-data' type='text' name='bl-end'></td>" + "</tr>" + "<tr>" + "<td><input class='bl-button bl-done' type='button' value='Done'></td>" + "<td></td>" + "<td><input class='bl-button bl-reset' type='button' value='Reset'></td>" + "</tr>" + "</table>" + "<textarea class='bl-URL'>" + "Generated URL goes here" + "</textarea>" + "</div>" + "</div>" + "<div class='bl-bottom'>" + "Source URL:" + "<a class='bl-srcURL'></a>" + "</div>" + "</div>").appendTo("body");
    };

    VideoClipper.prototype.getCaretPosition = function(editableDiv) {
      var containerEl, range, sel, temp1, temp2;

      this.caretPos = 0;
      containerEl = null;
      sel = void 0;
      range = void 0;
      if (window.getSelection) {
        sel = window.getSelection();
        if (sel.rangeCount) {
          range = sel.getRangeAt(0);
          if (range.commonAncestorContainer.parentNode === editableDiv) {
            temp1 = range.endContainer.data;
            temp2 = range.commonAncestorContainer.parentNode.innerHTML.replace(/&nbsp;/g, String.fromCharCode(160));
            temp2 = this.stripHTML(temp2);
            this.caretPos = range.endOffset + temp2.split(temp1)[0].length;
          }
        }
      }
      return this.caretPos;
    };

    VideoClipper.prototype.stripHTML = function(html) {
      var tmp;

      tmp = document.createElement("DIV");
      tmp.innerHTML = html;
      return tmp.textContent || tmp.innerText;
    };

    return VideoClipper;

  })();

}).call(this);
