// Generated by CoffeeScript 1.6.2
(function() {
  this.OmniPlayer = (function() {
    OmniPlayer.prototype.type = void 0;

    OmniPlayer.prototype.videoId = void 0;

    OmniPlayer.prototype.height = void 0;

    OmniPlayer.prototype.width = void 0;

    OmniPlayer.prototype.elementId = void 0;

    OmniPlayer.prototype.startSeconds = void 0;

    OmniPlayer.prototype.endSeconds = void 0;

    OmniPlayer.prototype.internal = void 0;

    OmniPlayer.loaded = {
      YT: false,
      TEST: false,
      JW: false
    };

    function OmniPlayer(obj) {
      this.elementId = obj.elementId;
      this.videoId = obj.videoId;
      this.type = obj.type;
      this.height = obj.height;
      this.width = obj.width;
      this.startSeconds = obj.startSeconds;
      this.endSeconds = obj.endSeconds;
      this.mediaContentUrl = obj.mediaContentUrl;
      this.thumbnailUrl = obj.thumbnailUrl;
      if (this.height == null) {
        this.height = $("#" + this.elementId).height();
      }
      if (this.width == null) {
        this.width = $("#" + this.elementId).width();
      }
      OmniPlayer[this.type].createPlayer.apply(this, [obj]);
    }

    OmniPlayer.prototype.getDuration = function() {
      throw new Error("getDuration isn't defined for OmniPlayer type " + this.type);
    };

    OmniPlayer.prototype.getCurrentTime = function() {
      throw new Error("getCurrentTime isn't not defined for OmniPlayer type " + this.type);
    };

    OmniPlayer.prototype.stopVideo = function() {
      throw new Error("stopVideo isn't not defined for OmniPlayer type " + this.type);
    };

    OmniPlayer.prototype.cueVideoById = function(options) {
      throw new Error("cueVideoById isn't not defined for OmniPlayer type " + this.type);
    };

    OmniPlayer.prototype.cueVideoByUrl = function(options) {
      throw new Error("cueVideoByUrl isn't not defined for OmniPlayer type " + this.type);
    };

    OmniPlayer.prototype.loadVideoById = function(options) {
      throw new Error("loadVideoById isn't not defined for OmniPlayer type " + this.type);
    };

    OmniPlayer.prototype.loadVideoById = function(options) {
      throw new Error("loadVideoByUrl isn't not defined for OmniPlayer type " + this.type);
    };

    OmniPlayer.prototype.remove = function() {
      var el, new_el;

      el = $("#" + this.elementId);
      new_el = el.after("<div></div>").next();
      el.remove();
      new_el.attr({
        id: "" + this.elementId
      });
      return this;
    };

    OmniPlayer.JW = {
      setup: function(started) {
        var that;

        if ((this.mediaContentUrl == null) && (this.videoId != null)) {
          this.mediaContentUrl = "http://www.youtube.com/watch?v=" + this.videoId;
        }
        if ((this.thumbnailUrl == null) && (this.videoId != null)) {
          this.thumbnailUrl = "http://img.youtube.com/vi/" + this.videoId + "/0.jpg";
        }
        this.internal = jwplayer(this.elementId).setup({
          file: this.mediaContentUrl,
          image: this.thumbnailUrl,
          height: this.height,
          width: this.width
        });
        that = this;
        this.internal.seek(this.startSeconds);
        this.internal.onPlay(function() {
          if (!started) {
            started = true;
            return that.internal.pause();
          }
        });
        this.internal.onTime(function(e) {
          if (e.position > that.endSeconds) {
            return that.stopVideo();
          }
        });
        return this.internal.onIdle(function(e) {
          started = false;
          return that.internal.seek(that.startSeconds);
        });
      },
      build: function(obj) {
        OmniPlayer.JW.setup.apply(this, [false]);
        this.getDuration = function() {
          return this.internal.getDuration();
        };
        this.getCurrentTime = function() {
          return this.internal.getPosition();
        };
        this.stopVideo = function() {
          return this.internal.stop();
        };
        this.cueVideoByUrl = function(options) {
          if (this.internal != null) {
            this.internal.remove();
          }
          this.endSeconds = options.endSeconds;
          this.startSeconds = options.startSeconds;
          this.mediaContentUrl = options.mediaContentUrl;
          this.thumbnailUrl = options.thumbnailUrl;
          return OmniPlayer.JW.setup.apply(this, [false]);
        };
        this.cueVideoById = function(options) {
          if (this.internal != null) {
            this.internal.remove();
          }
          this.endSeconds = options.endSeconds;
          this.startSeconds = options.startSeconds;
          this.videoId = options.videoId;
          return OmniPlayer.JW.setup.apply(this, [false]);
        };
        this.loadVideoById = function(options) {
          if (this.internal != null) {
            this.internal.remove();
          }
          this.endSeconds = options.endSeconds;
          this.startSeconds = options.startSeconds;
          this.videoId = options.videoId;
          return OmniPlayer.JW.setup.apply(this, [true]);
        };
        this.loadVideoByUrl = function(options) {
          if (this.internal != null) {
            this.internal.remove();
          }
          this.endSeconds = options.endSeconds;
          this.startSeconds = options.startSeconds;
          this.mediaContentUrl = options.mediaContentUrl;
          this.thumbnailUrl = options.thumbnailUrl;
          return OmniPlayer.JW.setup.apply(this, [true]);
        };
        return this.remove = function() {
          return this.internal.remove();
        };
      },
      createPlayer: function(obj) {
        if (jwplayer.key != null) {
          OmniPlayer.JW.build.apply(this, [obj]);
          return OmniPlayer.loaded.JW = true;
        } else {
          throw new Error('jwplayer.key is not defined');
        }
      }
    };

    OmniPlayer.YT = {
      setup: function() {
        var firstScriptTag, tag;

        tag = document.createElement("script");
        tag.src = "https://www.youtube.com/iframe_api";
        firstScriptTag = document.getElementsByTagName("script")[0];
        return firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
      },
      build: function() {
        var _this = this;

        this.internal = new window.YT.Player(this.elementId, {
          videoId: this.videoId,
          height: this.height,
          width: this.width,
          events: {
            onReady: function(event) {
              if (_this.startSeconds || _this.endSeconds) {
                return event.target.cueVideoById({
                  videoId: _this.videoId,
                  startSeconds: _this.startSeconds,
                  endSeconds: _this.endSeconds,
                  suggestedQuality: "large"
                });
              } else {
                _this.startSeconds = 0;
                return _this.endSeconds = _this.endSeconds || _this.getDuration();
              }
            }
          }
        });
        this.getDuration = function() {
          return this.internal.getDuration();
        };
        this.getCurrentTime = function() {
          return this.internal.getCurrentTime();
        };
        this.stopVideo = function() {
          return this.internal.stopVideo();
        };
        this.cueVideoByUrl = function(options) {
          if (options.suggestedQuality == null) {
            options.suggestedQuality = "large";
          }
          return this.internal.cueVideoByUrl = options;
        };
        this.cueVideoById = function(options) {
          if (options.suggestedQuality == null) {
            options.suggestedQuality = "large";
          }
          return this.internal.cueVideoById(options);
        };
        this.loadVideoById = function(options) {
          if (options.suggestedQuality == null) {
            options.suggestedQuality = "large";
          }
          return this.internal.loadVideoById(options);
        };
        return this.loadVideoByUrl = function(options) {
          if (options.suggestedQuality == null) {
            options.suggestedQuality = "large";
          }
          return this.internal.loadVideoByUrl = options;
        };
      },
      createPlayer: function(obj) {
        var that;

        that = this;
        if (OmniPlayer.loaded.YT) {
          return OmniPlayer.YT.build.apply(this);
        } else {
          window.onYouTubeIframeAPIReady = function() {
            OmniPlayer.loaded.YT = true;
            return OmniPlayer.YT.build.apply(that);
          };
          return OmniPlayer.YT.setup();
        }
      }
    };

    OmniPlayer.TEST = {
      createPlayer: function(obj) {
        OmniPlayer.loaded.TEST = true;
        this.getDuration = function() {
          return 0;
        };
        this.getCurrentTime = function() {
          return 0;
        };
        this.stopVideo = function() {
          return 0;
        };
        this.cueVideoById = function(options) {
          return 0;
        };
        this.cueVideoByUrl = function(options) {
          return 0;
        };
        this.loadVideoById = function(options) {
          return 0;
        };
        return this.loadVideoByUrl = function(options) {
          return 0;
        };
      }
    };

    return OmniPlayer;

  })();

}).call(this);
